"""create tenant core models

Revision ID: 37f4ca8b476b
Revises:
Create Date: 2026-07-28 20:47:02.720760

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "37f4ca8b476b"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "organizations",
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("legal_name", sa.String(length=240), nullable=True),
        sa.Column("slug", sa.String(length=100), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "active",
                "suspended",
                "closed",
                name="organization_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("support_email", sa.String(length=254), nullable=True),
        sa.Column("phone", sa.String(length=40), nullable=True),
        sa.Column("website", sa.String(length=500), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("organizations", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_organizations_slug"), ["slug"], unique=True)

    op.create_table(
        "users",
        sa.Column("email", sa.String(length=254), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("first_name", sa.String(length=100), nullable=False),
        sa.Column("last_name", sa.String(length=100), nullable=False),
        sa.Column("phone", sa.String(length=40), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "active",
                "inactive",
                "locked",
                name="user_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("is_platform_super_admin", sa.Boolean(), nullable=False),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_users_email"), ["email"], unique=True)

    op.create_table(
        "buildings",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("code", sa.String(length=50), nullable=True),
        sa.Column("address_line", sa.String(length=300), nullable=True),
        sa.Column("district", sa.String(length=100), nullable=True),
        sa.Column("city", sa.String(length=100), nullable=True),
        sa.Column("postal_code", sa.String(length=20), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organization_id", "code", name="uq_buildings_org_code"),
        sa.UniqueConstraint("organization_id", "id", name="uq_buildings_org_id"),
    )
    with op.batch_alter_table("buildings", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_buildings_organization_id"), ["organization_id"], unique=False
        )

    op.create_table(
        "organization_brandings",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("company_display_name", sa.String(length=160), nullable=True),
        sa.Column("logo_storage_key", sa.String(length=500), nullable=True),
        sa.Column("small_logo_storage_key", sa.String(length=500), nullable=True),
        sa.Column("favicon_storage_key", sa.String(length=500), nullable=True),
        sa.Column("primary_color", sa.String(length=7), nullable=True),
        sa.Column("secondary_color", sa.String(length=7), nullable=True),
        sa.Column("surface_color", sa.String(length=7), nullable=True),
        sa.Column("panel_title", sa.String(length=120), nullable=True),
        sa.Column("login_message", sa.String(length=500), nullable=True),
        sa.Column("white_label_enabled", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organization_id"),
    )
    op.create_table(
        "organization_domains",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("hostname", sa.String(length=253), nullable=False),
        sa.Column(
            "domain_type",
            sa.Enum(
                "platform_subdomain",
                "custom_domain",
                name="domain_type",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "state",
            sa.Enum(
                "pending",
                "awaiting_dns",
                "dns_verified",
                "ssl_pending",
                "active",
                "failed",
                "suspended",
                name="domain_state",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("verification_token", sa.String(length=255), nullable=True),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ssl_issued_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_primary", sa.Boolean(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("failure_reason", sa.String(length=500), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("hostname"),
    )
    with op.batch_alter_table("organization_domains", schema=None) as batch_op:
        batch_op.create_index(
            "ix_organization_domains_org_state", ["organization_id", "state"], unique=False
        )
        batch_op.create_index(
            "uq_organization_domains_primary_per_org",
            ["organization_id"],
            unique=True,
            postgresql_where=sa.text("is_primary"),
            sqlite_where=sa.text("is_primary = 1"),
        )

    op.create_table(
        "organization_memberships",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "role",
            sa.Enum(
                "organization_admin",
                "organization_member",
                name="organization_membership_role",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ends_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "ends_at IS NULL OR ends_at >= starts_at",
            name="ck_organization_memberships_valid_dates",
        ),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "organization_id", "user_id", name="uq_organization_memberships_org_user"
        ),
    )
    with op.batch_alter_table("organization_memberships", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_organization_memberships_organization_id"),
            ["organization_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_organization_memberships_user_id"), ["user_id"], unique=False
        )

    op.create_table(
        "apartments",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("building_id", sa.Uuid(), nullable=False),
        sa.Column("number", sa.String(length=30), nullable=False),
        sa.Column("floor", sa.String(length=30), nullable=True),
        sa.Column("block", sa.String(length=30), nullable=True),
        sa.Column("unit_code", sa.String(length=60), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id", "building_id"],
            ["buildings.organization_id", "buildings.id"],
            name="fk_apartments_org_building",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("building_id", "unit_code", name="uq_apartments_building_unit_code"),
        sa.UniqueConstraint("organization_id", "id", name="uq_apartments_org_id"),
    )
    with op.batch_alter_table("apartments", schema=None) as batch_op:
        batch_op.create_index(
            "ix_apartments_org_building", ["organization_id", "building_id"], unique=False
        )

    op.create_table(
        "building_memberships",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("building_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "role",
            sa.Enum(
                "building_manager",
                "building_staff",
                name="building_membership_role",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ends_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "ends_at IS NULL OR ends_at >= starts_at", name="ck_building_memberships_valid_dates"
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "building_id"],
            ["buildings.organization_id", "buildings.id"],
            name="fk_building_memberships_org_building",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("building_memberships", schema=None) as batch_op:
        batch_op.create_index(
            "ix_building_memberships_org_user", ["organization_id", "user_id"], unique=False
        )
        batch_op.create_index(
            "uq_building_memberships_active_user",
            ["building_id", "user_id"],
            unique=True,
            postgresql_where=sa.text("is_active"),
            sqlite_where=sa.text("is_active = 1"),
        )

    op.create_table(
        "apartment_memberships",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("apartment_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "role",
            sa.Enum(
                "owner",
                "tenant",
                "resident",
                "authorized_person",
                name="apartment_membership_role",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ends_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "ends_at IS NULL OR ends_at >= starts_at", name="ck_apartment_memberships_valid_dates"
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "apartment_id"],
            ["apartments.organization_id", "apartments.id"],
            name="fk_apartment_memberships_org_apartment",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("apartment_memberships", schema=None) as batch_op:
        batch_op.create_index(
            "ix_apartment_memberships_apartment_period",
            ["apartment_id", "starts_at", "ends_at"],
            unique=False,
        )
        batch_op.create_index(
            "ix_apartment_memberships_org_user_active",
            ["organization_id", "user_id", "is_active"],
            unique=False,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("apartment_memberships", schema=None) as batch_op:
        batch_op.drop_index("ix_apartment_memberships_org_user_active")
        batch_op.drop_index("ix_apartment_memberships_apartment_period")

    op.drop_table("apartment_memberships")
    with op.batch_alter_table("building_memberships", schema=None) as batch_op:
        batch_op.drop_index(
            "uq_building_memberships_active_user",
            postgresql_where=sa.text("is_active"),
            sqlite_where=sa.text("is_active = 1"),
        )
        batch_op.drop_index("ix_building_memberships_org_user")

    op.drop_table("building_memberships")
    with op.batch_alter_table("apartments", schema=None) as batch_op:
        batch_op.drop_index("ix_apartments_org_building")

    op.drop_table("apartments")
    with op.batch_alter_table("organization_memberships", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_organization_memberships_user_id"))
        batch_op.drop_index(batch_op.f("ix_organization_memberships_organization_id"))

    op.drop_table("organization_memberships")
    with op.batch_alter_table("organization_domains", schema=None) as batch_op:
        batch_op.drop_index(
            "uq_organization_domains_primary_per_org",
            postgresql_where=sa.text("is_primary"),
            sqlite_where=sa.text("is_primary = 1"),
        )
        batch_op.drop_index("ix_organization_domains_org_state")

    op.drop_table("organization_domains")
    op.drop_table("organization_brandings")
    with op.batch_alter_table("buildings", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_buildings_organization_id"))

    op.drop_table("buildings")
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_email"))

    op.drop_table("users")
    with op.batch_alter_table("organizations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_organizations_slug"))

    op.drop_table("organizations")
    # ### end Alembic commands ###
