"""add charge and payment core

Revision ID: c55f4ab1bcf3
Revises: 37f4ca8b476b
Create Date: 2026-07-28 22:07:39.202926

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "c55f4ab1bcf3"
down_revision = "37f4ca8b476b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "charge_batches",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("building_id", sa.Uuid(), nullable=False),
        sa.Column("period_year", sa.Integer(), nullable=False),
        sa.Column("period_month", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=160), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=True),
        sa.Column("default_amount", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("due_date", sa.Date(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "draft",
                "posted",
                "cancelled",
                name="charge_batch_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("default_amount > 0", name="ck_charge_batches_positive_amount"),
        sa.CheckConstraint("period_month BETWEEN 1 AND 12", name="ck_charge_batches_period_month"),
        sa.ForeignKeyConstraint(["created_by_user_id"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["organization_id", "building_id"],
            ["buildings.organization_id", "buildings.id"],
            name="fk_charge_batches_org_building",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organization_id", "id", name="uq_charge_batches_org_id"),
    )
    with op.batch_alter_table("charge_batches", schema=None) as batch_op:
        batch_op.create_index(
            "ix_charge_batches_org_building_period",
            ["organization_id", "building_id", "period_year", "period_month"],
            unique=False,
        )
        batch_op.create_index(
            "uq_charge_batches_posted_period",
            ["building_id", "period_year", "period_month"],
            unique=True,
            postgresql_where=sa.text("status = 'posted'"),
            sqlite_where=sa.text("status = 'posted'"),
        )

    op.create_table(
        "charges",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("building_id", sa.Uuid(), nullable=False),
        sa.Column("apartment_id", sa.Uuid(), nullable=False),
        sa.Column("charge_batch_id", sa.Uuid(), nullable=True),
        sa.Column(
            "charge_type",
            sa.Enum(
                "monthly_due",
                "additional_due",
                "manual",
                name="charge_type",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("title", sa.String(length=160), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=True),
        sa.Column("period_year", sa.Integer(), nullable=True),
        sa.Column("period_month", sa.Integer(), nullable=True),
        sa.Column("original_amount", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("due_date", sa.Date(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "draft",
                "posted",
                "reversed",
                name="charge_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("reversed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reversal_reason", sa.String(length=500), nullable=True),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("original_amount > 0", name="ck_charges_positive_amount"),
        sa.CheckConstraint(
            "period_month IS NULL OR period_month BETWEEN 1 AND 12", name="ck_charges_period_month"
        ),
        sa.ForeignKeyConstraint(["created_by_user_id"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["organization_id", "apartment_id"],
            ["apartments.organization_id", "apartments.id"],
            name="fk_charges_org_apartment",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "building_id"],
            ["buildings.organization_id", "buildings.id"],
            name="fk_charges_org_building",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "charge_batch_id"],
            ["charge_batches.organization_id", "charge_batches.id"],
            name="fk_charges_org_batch",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organization_id", "id", name="uq_charges_org_id"),
    )
    with op.batch_alter_table("charges", schema=None) as batch_op:
        batch_op.create_index("ix_charges_charge_batch_id", ["charge_batch_id"], unique=False)
        batch_op.create_index(
            "ix_charges_org_apartment_status_due",
            ["organization_id", "apartment_id", "status", "due_date"],
            unique=False,
        )

    op.create_table(
        "payments",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("building_id", sa.Uuid(), nullable=False),
        sa.Column("apartment_id", sa.Uuid(), nullable=False),
        sa.Column("payer_user_id", sa.Uuid(), nullable=True),
        sa.Column("amount", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("payment_date", sa.Date(), nullable=False),
        sa.Column(
            "payment_method",
            sa.Enum(
                "cash",
                "bank_transfer",
                "card",
                "other",
                name="payment_method",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("reference", sa.String(length=120), nullable=True),
        sa.Column("description", sa.String(length=500), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "posted",
                "reversed",
                name="payment_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("reversed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reversal_reason", sa.String(length=500), nullable=True),
        sa.Column("recorded_by_user_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("amount > 0", name="ck_payments_positive_amount"),
        sa.ForeignKeyConstraint(
            ["organization_id", "apartment_id"],
            ["apartments.organization_id", "apartments.id"],
            name="fk_payments_org_apartment",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "building_id"],
            ["buildings.organization_id", "buildings.id"],
            name="fk_payments_org_building",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(["payer_user_id"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["recorded_by_user_id"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organization_id", "id", name="uq_payments_org_id"),
    )
    with op.batch_alter_table("payments", schema=None) as batch_op:
        batch_op.create_index(
            "ix_payments_org_apartment_status_date",
            ["organization_id", "apartment_id", "status", "payment_date"],
            unique=False,
        )

    op.create_table(
        "payment_allocations",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("payment_id", sa.Uuid(), nullable=False),
        sa.Column("charge_id", sa.Uuid(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint("amount > 0", name="ck_payment_allocations_positive_amount"),
        sa.ForeignKeyConstraint(
            ["organization_id", "charge_id"],
            ["charges.organization_id", "charges.id"],
            name="fk_allocations_org_charge",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "payment_id"],
            ["payments.organization_id", "payments.id"],
            name="fk_allocations_org_payment",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "payment_id", "charge_id", name="uq_payment_allocations_payment_charge"
        ),
    )
    with op.batch_alter_table("payment_allocations", schema=None) as batch_op:
        batch_op.create_index(
            "ix_payment_allocations_org_charge", ["organization_id", "charge_id"], unique=False
        )
        batch_op.create_index(
            "ix_payment_allocations_org_payment", ["organization_id", "payment_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("payment_allocations", schema=None) as batch_op:
        batch_op.drop_index("ix_payment_allocations_org_payment")
        batch_op.drop_index("ix_payment_allocations_org_charge")

    op.drop_table("payment_allocations")
    with op.batch_alter_table("payments", schema=None) as batch_op:
        batch_op.drop_index("ix_payments_org_apartment_status_date")

    op.drop_table("payments")
    with op.batch_alter_table("charges", schema=None) as batch_op:
        batch_op.drop_index("ix_charges_org_apartment_status_due")
        batch_op.drop_index("ix_charges_charge_batch_id")

    op.drop_table("charges")
    with op.batch_alter_table("charge_batches", schema=None) as batch_op:
        batch_op.drop_index(
            "uq_charge_batches_posted_period",
            postgresql_where=sa.text("status = 'posted'"),
            sqlite_where=sa.text("status = 'posted'"),
        )
        batch_op.drop_index("ix_charge_batches_org_building_period")

    op.drop_table("charge_batches")
    # ### end Alembic commands ###
