"""add standard data import tracking

Revision ID: e5bcf7b6291d
Revises: c55f4ab1bcf3
Create Date: 2026-07-29 14:52:19.849200

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "e5bcf7b6291d"
down_revision = "c55f4ab1bcf3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "import_runs",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("source_system", sa.String(length=60), nullable=False),
        sa.Column("dataset_name", sa.String(length=200), nullable=False),
        sa.Column("dataset_version", sa.String(length=30), nullable=False),
        sa.Column("schema_version", sa.String(length=30), nullable=False),
        sa.Column("manifest_sha256", sa.String(length=64), nullable=False),
        sa.Column("package_fingerprint", sa.String(length=64), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "running",
                "completed",
                "failed",
                name="import_run_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("site_count", sa.Integer(), nullable=False),
        sa.Column("unit_count", sa.Integer(), nullable=False),
        sa.Column("resident_count", sa.Integer(), nullable=False),
        sa.Column("charge_count", sa.Integer(), nullable=False),
        sa.Column("payment_count", sa.Integer(), nullable=False),
        sa.Column("expense_count", sa.Integer(), nullable=False),
        sa.Column("announcement_count", sa.Integer(), nullable=False),
        sa.Column("inserted_count", sa.Integer(), nullable=False),
        sa.Column("updated_count", sa.Integer(), nullable=False),
        sa.Column("skipped_count", sa.Integer(), nullable=False),
        sa.Column("error_count", sa.Integer(), nullable=False),
        sa.Column("error_summary", sa.Text(), nullable=True),
        sa.Column("metadata", sa.JSON(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["created_by_user_id"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("import_runs", schema=None) as batch_op:
        batch_op.create_index(
            "ix_import_runs_org_started", ["organization_id", "started_at"], unique=False
        )
        batch_op.create_index(
            "uq_import_runs_completed_fingerprint",
            ["organization_id", "source_system", "package_fingerprint"],
            unique=True,
            postgresql_where=sa.text("status = 'completed'"),
            sqlite_where=sa.text("status = 'completed'"),
        )
        batch_op.create_index(
            "uq_import_runs_org_running",
            ["organization_id"],
            unique=True,
            postgresql_where=sa.text("status = 'running'"),
            sqlite_where=sa.text("status = 'running'"),
        )

    op.create_table(
        "external_record_maps",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("source_system", sa.String(length=60), nullable=False),
        sa.Column("entity_type", sa.String(length=40), nullable=False),
        sa.Column("source_key", sa.String(length=200), nullable=False),
        sa.Column("internal_id", sa.Uuid(), nullable=False),
        sa.Column("first_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("import_run_id", sa.Uuid(), nullable=False),
        sa.Column("source_payload_hash", sa.String(length=64), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["import_run_id"], ["import_runs.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "organization_id",
            "source_system",
            "entity_type",
            "source_key",
            name="uq_external_record_maps_source_key",
        ),
    )
    with op.batch_alter_table("external_record_maps", schema=None) as batch_op:
        batch_op.create_index(
            "ix_external_record_maps_internal",
            ["organization_id", "entity_type", "internal_id"],
            unique=False,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("external_record_maps", schema=None) as batch_op:
        batch_op.drop_index("ix_external_record_maps_internal")

    op.drop_table("external_record_maps")
    with op.batch_alter_table("import_runs", schema=None) as batch_op:
        batch_op.drop_index(
            "uq_import_runs_org_running",
            postgresql_where=sa.text("status = 'running'"),
            sqlite_where=sa.text("status = 'running'"),
        )
        batch_op.drop_index(
            "uq_import_runs_completed_fingerprint",
            postgresql_where=sa.text("status = 'completed'"),
            sqlite_where=sa.text("status = 'completed'"),
        )
        batch_op.drop_index("ix_import_runs_org_started")

    op.drop_table("import_runs")
    # ### end Alembic commands ###
