SOURCE_SYSTEM_STANDARD_EXCEL = "standard_excel"
SUPPORTED_SCHEMA_VERSION = "1.0"
SUPPORTED_CURRENCY = "TRY"

ENTITY_SITE = "site"
ENTITY_UNIT = "unit"
ENTITY_RESIDENT = "resident"
ENTITY_CHARGE = "charge"
ENTITY_PAYMENT = "payment"
ENTITY_EXPENSE = "expense"
ENTITY_BANK_TRANSACTION = "bank_transaction"
ENTITY_ANNOUNCEMENT = "announcement"

MAPPED_ENTITY_TYPES = {
    ENTITY_SITE,
    ENTITY_UNIT,
    ENTITY_RESIDENT,
    ENTITY_CHARGE,
    ENTITY_PAYMENT,
    ENTITY_EXPENSE,
    ENTITY_BANK_TRANSACTION,
    ENTITY_ANNOUNCEMENT,
}
